# Generated by Django 3.2.6 on 2023-04-05 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Username')),
                ('fullname', models.CharField(blank=True, max_length=130, verbose_name='full name')),
                ('sex', models.CharField(blank=True, default='MALE', max_length=10, null=True, verbose_name='Gender')),
                ('option', models.CharField(blank=True, default='NONE', max_length=10, null=True, verbose_name='Option')),
                ('authorities', models.CharField(choices=[('admin', 'admin'), ('principal', 'principal'), ('academic', 'academic'), ('staff', 'staff'), ('student', 'student')], max_length=30, verbose_name='Role authorities')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Mockexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.JSONField(blank=True, null=True, verbose_name='Subjects')),
                ('marks', models.JSONField(blank=True, null=True, verbose_name='Marks')),
                ('grade', models.JSONField(blank=True, null=True, verbose_name='Grade')),
                ('point', models.IntegerField(verbose_name='grade point')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Mockexam',
            },
        ),
    ]
