# Generated by Django 3.2.6 on 2023-04-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock2023', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockexam',
            name='marks',
        ),
        migrations.AddField(
            model_name='mockexam',
            name='division',
            field=models.CharField(default=1, max_length=10, verbose_name='Division'),
            preserve_default=False,
        ),
    ]
